name: Deploy Github Pages
on:
  push:
    branches: gatsby-master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:12-buster
    steps:
    - uses: actions/checkout@v1
    - name: Setup Git
      run: git config --global user.email duzzifelipe@gmail.com
    - name: Setup Global
      run: yarn global add gatsby-cli
    - name: Setup Package Caching
      id: modules_cache
      uses: actions/cache@v1
      with:
        path: node_modules/
        key: deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: deps-
    - name: Install Packages
      run: yarn install
    - name: Build App
      run: yarn run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
